### ISSUE TITLE
Domain is case sensitive

### ISSUE THREAD

**Issue by stephan-koch** [rumart/GlobalDashboardPS#12]
Hi, recognized that the name of the AD Doomain is case sensitive.
In my case "demo.local" is not working if the Domain is defined with "Demo.local"

Thanks for your effort here, Good to have an real API for GD.

**Comment by rumart** [comment]
Hi
I suspect this is an issue with the GlobalDashboard API and not the powershell module. The code is not doing anything to the domain/directory.
I have switched jobs since I created this module and have no access to a GlobalDashboard environment so can't really verify.

If you want to investigate and verify this your self I would suggest trying logging in directly to the API , check [this post](https://developer.hpe.com/blog/accessing-the-hpe-oneview-global-dashboard-api) for more info

**Comment by stephan-koch** [comment]
you are absolutly right.
Thanks for your help
